version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports: 
      - '5432:5432'
  animalsservice:
    build:
      context: ./animals-service
    environment:
      APP_PORT: 8080
      PG_DATABASE: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USERNAME: postgres
      PG_PASSWORD: 1234
    depends_on:
      - postgres
    ports:
      - '8080:8080'
volumes:
  db-data:
    external: true